name: async_events
description: A portable asynchronous event hub supporting multiple storage types
version: 1.3.0
homepage: https://github.com/gmpassos/async_events

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  async_extension: ^1.2.14
  collection: ^1.19.0
  logging: ^1.3.0
  reflection_factory: ^2.5.1

dev_dependencies:
  lints: ^5.1.1
  build_runner: ^2.4.15
  build_verify: ^3.1.0
  dependency_validator: ^3.2.3
  test: ^1.25.15

#dependency_overrides:
#  reflection_factory:
#    path: ../reflection_factory

